#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1541494972                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A beautiful Twitter widget for iOS.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : James Shaw
your_link                                 : https://shaw-james.com
your_city                                 : York, England
email_address                             :
facebook_username                         :
instagram_username                        : jsh8w
twitter_username                          : jsh8w
github_username                           : jsh8w
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Live Twitter Timeline
    description                           : View your live Twitter timeline right on your iPhone home screen.
    fontawesome_icon_name                 : hashtag

  - title                                 : Beautiful iOS 14 Widget
    description                           : Designed for specifically for iOS 14 Devices and the Apple WidgetKit SDK.
    fontawesome_icon_name                 : mobile

  - title                                 : 3 Widget Sizes
    description                           : Use Twidget in small, medium or large; each showing different content.
    fontawesome_icon_name                 : window-maximize

  - title                                 : 3 Widget Themes
    description                           : Customise the style of widgets by selecting the light, dark or blue themes.
    fontawesome_icon_name                 : palette

  - title                                 : Auto-refreshing Timelime
    description                           : Twidget updates automatically to keep your Twitter timeline in sync.
    fontawesome_icon_name                 : sync

  - title                                 : Feature Requests
    description                           : If you have any feature requests, feedback or questions; please don't hesitate to get in touch.
    fontawesome_icon_name                 : question



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#00acee"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#00acee"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
